"""Add human review to interaction

Revision ID: 4c197c7317db
Revises: 0001_initial_schema
Create Date: 2026-08-29 16:19:22.091339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c197c7317db'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('human_review', sa.String(length=32), nullable=True))
    op.drop_index('ix_policy_configs_org_use_case', table_name='policy_configs')
    op.create_index(op.f('ix_policy_configs_org_id'), 'policy_configs', ['org_id'], unique=False)
    op.create_index(op.f('ix_policy_configs_use_case'), 'policy_configs', ['use_case'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_configs_use_case'), table_name='policy_configs')
    op.drop_index(op.f('ix_policy_configs_org_id'), table_name='policy_configs')
    op.create_index('ix_policy_configs_org_use_case', 'policy_configs', ['org_id', 'use_case'], unique=False)
    op.drop_column('interactions', 'human_review')
    # ### end Alembic commands ###
